switcher++: switcher.c
	g++ -o switcher++ switcher.c
switcher--: switcher.c
	gcc -o switcher-- switcher.c
switchcond++: switchcond.c
	g++ -o switchcond++ switchcond.c
switchcond--: switchcond.c
	gcc -o switchcond-- switchcond.c
all: switcher++ switcher--
clean:
	rm switcher++ switcher--
